### ISSUE TITLE
Split requirements

### ISSUE THREAD

**Issue by nnadeau** [nnadeau/pybotics#128]
## Expected Behavior
- `requirements` folder with several requirements files

## Actual Behavior
- Only two requirements files
- `ci-requirements.txt` is becoming quite large and causing dependecy checking issues

**Comment by nnadeau** [comment]
Example from https://pyup.io/docs/configuration/:
```
# adding requirements files manually, default is empty
requirements:
  - requirements/staging.txt:
      # update all dependencies and pin them
      updates: all
      pin: True
  - requirements/dev.txt:
      # don't update dependencies, use global default for pinning
      updates: False
  - requirements/prod.txt:
      # update insecure dependencies only, pin all dependencies
      updates: insecure
      pin: True
```
